name = input("Enter your name: ")

result = len(name)
# result = name.find("a")
# result = name.rfind("y")
# result = name.count("a")
# result = name.capitalize()
# result = name.upper()
# result = name.lower()
# result = name.isdigit()
# result = name.isalpha()
# result = name.endswith("Y")
print(result)
